version "4.1.3"

#include "ZScript/NashGore/NashGoreCommon.zc"
#include "ZScript/NashGore/NashGoreStatics.zc"
#include "ZScript/NashGore/NashGoreHandler.zc"
#include "ZScript/NashGore/NashGoreBlood.zc"
#include "ZScript/NashGore/NashGoreBloodPlane.zc"
#include "ZScript/NashGore/NashGoreGibs.zc"
#include "ZScript/NashGore/NashGoreCrushedGibs.zc"
#include "ZScript/NashGore/NashGoreSquishyGibs.zc"
#include "ZScript/NashGore/NashGoreIceChunk.zc"
#include "ZScript/NashGore/NashGoreLiquidBlood.zc"
#include "ZScript/NashGore/NashGoreWallBlood.zc"
#include "ZScript/NashGore/NashGoreActor.zc"
#include "ZScript/NashGore/NashGoreMenu.zc"

// global constants
const STAT_NashGore_Gore = Thinker.STAT_USER + 1;
