// Enemy projectiles: HDE visuals, Halo CE impact damage
class HCE_ARBullet : HCES_ARBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 10;
	}
}

class HCE_BattleRifleARBullet : HCES_ARBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 12;
	}
}

class HCE_H2BeamShot : HCE_BeamPuff
{
	Default
	{
	}
}

class HCE_BulldogBuckshot : HCES_ShotgunPellet
{
	Default
	{
		HCES_Projectile.BaseDamage 7;
	}
}

class HCE_CommandoARBullet : HCES_ARBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 14;
	}
}

class HCE_DMRSniperBullet : HCES_SniperBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 24;
	}
}

class HCE_DBLShotgunPellet : HCES_ShotgunPellet
{
	Default
	{
		HCES_Projectile.BaseDamage 9;
	}
}

class HCE_Flame : HCES_Flame
{
	Default
	{
	}
}

class HCE_FuelRodBolt : HCES_FuelRod
{
	Default
	{
	}
}

class HCE_GPMGBullet : HCES_ARBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 15;
	}
}

class HCE_40mmGrenade : HCES_FragGrenade
{
	Default
	{
	}
}

class HCE_HydraMissile : HCES_Rocket
{
	Default
	{
	}
}

class HCE_MA37Round : HCES_ARBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 9;
	}
}

class HCE_Needle : HCES_Needle
{
	Default
	{
	}
}

class HCE_PistolBullet : HCES_PistolBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 25;
	}
}

class HCE_PlasmaCasterGrenade : HCES_PlasmaCasterProj
{
	Default
	{
	}
}

class HCE_PlasmaPistolBolt : HCES_PlasmaPistolBolt
{
	Default
	{
		HCES_Projectile.BaseDamage 18;
	}
}

class HCE_PlasmaRifleBolt : HCES_PlasmaRifleBolt
{
	Default
	{
		HCES_Projectile.BaseDamage 13;
	}
}

class HCE_Rocket : HCES_Rocket
{
	Default
	{
	}
}

class HCE_ShotgunPellet : HCES_ShotgunPellet
{
	Default
	{
		HCES_Projectile.BaseDamage 20;
	}
}

class HCE_SidekickRound : HCES_PistolBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 18;
	}
}

class HCE_SMGRound : HCES_ARBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 6;
	}
}

class HCE_SniperBullet : HCES_SniperBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 101;
	}
}

class HCE_StanchionRail : HCES_SniperBullet
{
	Default
	{
		HCES_Projectile.BaseDamage 150;
	}
}

class HCE_StickyDetCharge : HCES_PlasmaGrenade
{
	Default
	{
	}
}

class HCE_ChargedPlasma : HCES_ChargedPlasma
{
	Default
	{
		HCES_Projectile.BaseDamage 70;
	}
}
